services:
  - type: web
    name: car-service-backend
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarService
    buildCommand: ./mvnw package -DskipTests

  - type: web
    name: car-admin-monitor
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarAdminMonitor
    buildCommand: ./mvnw package -DskipTests

  - type: web
    name: car-listener-service
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarListnerService
    buildCommand: ./mvnw package -DskipTests

  - type: web
    name: car-service-frontend
    env: node
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarRentalWebApp
    buildCommand: npm install && npm run build --prod
    startCommand: npx serve -s dist/car-rental-web-app
<<<<<<< HEAD
=======

>>>>>>> 935782cf198abe0a9a8857579ca591759762b962
