services:
  - type: web
    name: car-service-backend
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarService

  - type: web
    name: car-admin-monitor
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarAdminMonitor

  - type: web
    name: car-listener-service
    runtime: docker
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarListnerService

  - type: web
    name: car-service-frontend
    env: node
    plan: free
    repo: https://github.com/cyberhackstar/CarRental
    rootDir: CarRentalWebApp
    buildCommand: npm install && npm run build --prod
    startCommand: npx serve -s dist/car-rental-web-app

