server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          
  - job_name: carservice
    static_configs:
      - targets:
          - localhost
        labels:
          job: carservice
          __path__: /app/logs/carservice/*.log

  - job_name: carlistnerservice
    static_configs:
      - targets:
          - localhost
        labels: 
          job: carlistnerservice
          __path__: /app/logs/carlistnerservice/*.log

  - job_name: caradminmonitor
    static_configs:
      - targets:
          - localhost
        labels:
          job: caradminmonitor
          __path__: /app/logs/caradminmonitor/*.log

  
