
server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # activemq:
  #   broker-url: ${ACTIVEMQ_URL}
  #   user: ${ACTIVEMQ_USER}
  #   password: ${ACTIVEMQ_PASSWORD}
  #   packages:
  #     trust-all: true

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: /app/logs/CarListner.log
