
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  # activemq:
  #   broker-url: ${ACTIVEMQ_URL}
  #   user: ${ACTIVEMQ_USER}
  #   password: ${ACTIVEMQ_PASSWORD}
  #   packages:
  #     trust-all: true


  rabbitmq:
    addresses: ${CLOUDAMQP_URL}


  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        instance:
          prefer-ip: true
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      jms:
        enabled: false



logging:
  file:
    name: /app/logs/CarService.log
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org:
      springframework:
        security: DEBUG

car:
  image:
    upload-dir: src/main/resources/static/uploads

razorpay:
  keyId: ${RAZORPAY_KEY_ID}
  keySecret: ${RAZORPAY_KEY_SECRET}
  currency: INR
  companyName: CarRental
  
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

